apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: node-react-k8s
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: registry.gitlab.com/hilal.ahmad.developer-group/k8s-node-frontend
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://localhost:3001/api/users"
