# Backend Deployment Configuration
apiVersion: apps/v1 # Kubernetes API version for Deployment
kind: Deployment # Resource type: Deployment
metadata:
  name: backend-deployment # Name of the deployment
  namespace: node-react-k8s # Kubernetes namespace
  labels:
    app: backend # Label to identify this deployment
spec:
  replicas: 3 # Number of pod replicas to maintain
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: # Pod selector configuration
      app: backend # Selects pods with label app=backend
  template:
    metadata:
      labels:
        app: backend # Labels for the pod template
    spec:
      containers:
        - name: backend # Container name
          image: registry.gitlab.com/hilal.ahmad.developer-group/k8s-node-backend # Container image location
          ports:
            - containerPort: 3000 # Port exposed by the container
          env:
            - name: MONGO_URI # Environment variable for MongoDB connection
              value: "mongodb://mongouser:mongopassword@mongodb-service:27017/mydb?authSource=admin"
              # valueFrom:
              #   secretKeyRef: # Reference to Kubernetes secret
              #     name: backend-secret # Name of the secret
              #     key: MONGODB_URI # Key in the secret
          resources: # Resource limits and requests
            limits: # Maximum resources allowed
              cpu: "500m" # 500 millicores (0.5 CPU)
              memory: "512Mi" # 512 Megabytes of memory
            requests: # Minimum resources needed
              cpu: "200m" # 200 millicores (0.2 CPU)
              memory: "256Mi" # 256 Megabytes of memory
