apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: node-react-k8s
  labels:
    app: mongodb-node
type: Opaque
data:
  # Base64 encoded secrets
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvbm9kZS1yZWFjdC1rOHM=
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RrZXk=
