# Specifies the Kubernetes API version being used
apiVersion: v1

# Defines the type of Kubernetes resource - in this case a Service
kind: Service

# Contains metadata about the service
metadata:
  # The name of the service that will be used to identify it
  name: backend-service

  # The namespace where the service will be created
  namespace: node-react-k8s

  # Labels to help identify the service
  labels:
    app: backend

# The specification section that defines the desired state of the service
spec:
  # Defines which pods the service will target based on their labels
  selector:
    # Targets pods with label app=backend
    app: backend

  # Defines the network ports for the service
  ports:
    # Port configuration for the service
    - protocol: TCP # Uses TCP protocol for communication
      port: 3000 # The port exposed by the service
      targetPort: 3000 # The port on the pod that the service forwards to

  # Specifies the service type as ClusterIP (internal access only)
  type: ClusterIP
