apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-node
  namespace: node-react-k8s
  labels:
    app: mongodb-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
