apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-node
  namespace: node-react-k8s
  labels:
    app: mongodb-node
type: Opaque
data:
  # Values must be base64 encoded
  mongo-root-username: bW9uZ291c2Vy # decoded: mongouser
  mongo-root-password: bW9uZ29wYXNzd29yZA== # decoded: mongopassword
