apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-node
  labels:
    app: mongodb-node
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/db
