apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: node-react-k8s
  labels:
    app: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://mongouser:mongopassword@mongodb-service:27017/mydb?authSource=admin"
