apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  namespace: node-react-k8s
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
